# Python_ML_DL Midterm Project


## 題目: 從頭實作 Linear regression 和 logistic regression

### 動機、程式說明

[資料來源](https://archive.ics.uci.edu/ml/datasets/Abalone)

### 功能

- Linear regression

- logistic regression

In [138]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import locale
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures


%run ./LinearRegression.ipynb #include這個file進來

In [139]:
def Replace(x):#把性別換成數字
    if x.values=='M':
        return 1
    elif x.values == 'F':
        return 2
    elif x.values == 'I':
        return 3

dataset = pd.read_csv('./abalone.data',header=None)
colnames = ['Sex','Length','Diameter','Height','Whole weight','Shucked weight','Viscera weight','Shell weight','Rings']
dataset.columns = colnames 
#dataset.isnull().any() 檢查過沒有null了
#dataset.shape =>(4177, 9)
#把X 和 Y分離開( feature 和 result)
Y= dataset.loc[:,['Rings']] 
X= dataset.drop(['Rings'],axis=1)
X.loc[:,['Sex']] = X.loc[:,['Sex']].apply(Replace, axis=1)#把性別換成數字


Addpolynomial(X,6)#代表要加入1~6次方的所有feature，例如 Sex，就會有新column Sex2 Sex3...Sex6 表示1~6次方
print(X.columns)
X.head()

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Sex2', 'Length2', 'Diameter2',
       'Height2', 'Whole weight2', 'Shucked weight2', 'Viscera weight2',
       'Shell weight2', 'Sex3', 'Length3', 'Diameter3', 'Height3',
       'Whole weight3', 'Shucked weight3', 'Viscera weight3', 'Shell weight3',
       'Sex4', 'Length4', 'Diameter4', 'Height4', 'Whole weight4',
       'Shucked weight4', 'Viscera weight4', 'Shell weight4', 'Sex5',
       'Length5', 'Diameter5', 'Height5', 'Whole weight5', 'Shucked weight5',
       'Viscera weight5', 'Shell weight5', 'Sex6', 'Length6', 'Diameter6',
       'Height6', 'Whole weight6', 'Shucked weight6', 'Viscera weight6',
       'Shell weight6'],
      dtype='object')

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Sex2,Length2,...,Viscera weight5,Shell weight5,Sex6,Length6,Diameter6,Height6,Whole weight6,Shucked weight6,Viscera weight6,Shell weight6
0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,1,0.207025,...,1.051010e-05,7.593750e-05,1,0.008873,0.002365,7.350919e-07,0.018441,1.280260e-04,1.061520e-06,1.139062e-05
1,1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,1,0.122500,...,2.683544e-07,1.680700e-06,1,0.001838,0.000346,5.314410e-07,0.000131,9.703725e-07,1.301519e-08,1.176490e-07
2,2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,4,0.280900,...,5.672601e-05,4.084101e-04,64,0.022164,0.005489,6.053445e-06,0.096279,2.847897e-04,8.026730e-06,8.576612e-05
3,1,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,1,0.193600,...,1.925415e-05,8.946610e-05,1,0.007256,0.002365,3.814697e-06,0.018875,1.001575e-04,2.194973e-06,1.386725e-05
4,3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,9,0.108900,...,9.615801e-08,5.032844e-07,729,0.001291,0.000275,2.621440e-07,0.000074,5.139705e-07,3.798241e-09,2.768064e-08

In [140]:
x_train,x_test,y_train,y_test =train_test_split(X,Y,test_size = 0.2, random_state = 4) #用80%做training set
LinearR_CallFunc(x_train,x_test,y_train,y_test)

Call Library得到的R^2分數: 0.5356348710674512